<?php declare(strict_types=1); use ReaCms\Plugin\SafeHtml; /** @var callable(mixed):string $escape */ /** @var array<string,mixed>|null $post */ /** @var list<array<string,mixed>> $media */ /** @var string $csrfToken */ $id=(int)($post['id']??0); ?>
<section><p class="eyebrow">Blogs</p><h1 class="mt-3 text-3xl font-bold"><?= $id ? 'Edit post' : 'New post' ?></h1>
<form class="panel mt-8 space-y-5" method="post" action="<?= $id ? '/cms/blog/'.$id : '/cms/blog' ?>">
<input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><label class="form-label">Title<input class="form-input" name="title" value="<?= $escape($post['title']??'') ?>" required></label>
<label class="form-label">Slug<input class="form-input" name="slug" value="<?= $escape($post['slug']??'') ?>" placeholder="Generated from title"></label>
<label class="form-label">Excerpt<textarea class="form-input" name="excerpt" rows="3"><?= $escape($post['excerpt']??'') ?></textarea></label>
<fieldset><legend class="form-label">Content</legend><div class="editor-toolbar" role="toolbar" aria-label="Text formatting">
<?php foreach ([['formatBlock','H2','Heading'],['bold','', 'Bold'],['italic','','Italic'],['underline','','Underline'],['insertUnorderedList','','Bullets'],['insertOrderedList','','Numbered'],['justifyLeft','','Left'],['justifyCenter','','Center']] as [$command,$value,$label]) : ?><button type="button" data-editor-command="<?= $escape($command) ?>" data-editor-value="<?= $escape($value) ?>"><?= $escape($label) ?></button><?php endforeach; ?>
<button type="button" data-editor-link>Link</button><button type="button" data-media-open>Insert image</button></div>
<div id="blog-editor" class="rich-editor" contenteditable="true"><?= SafeHtml::sanitize((string)($post['content']??''))->value ?></div><textarea id="blog-content" name="content" hidden></textarea></fieldset>
<label class="form-label">Featured image<select class="form-input" name="featured_media_id"><option value="">None</option><?php foreach ($media as $image) : ?><option value="<?= (int)$image['id'] ?>" <?= (int)($post['featured_media_id']??0)===(int)$image['id']?'selected':'' ?>><?= $escape($image['original_name']) ?></option><?php endforeach; ?></select></label>
<label class="form-label">Status<select class="form-input" name="status"><option value="draft">Draft</option><option value="published" <?= ($post['status']??'')==='published'?'selected':'' ?>>Published</option></select></label>
<div class="flex gap-3"><button class="button-primary" type="submit">Save post</button><a class="button-secondary" href="/cms/blog">Cancel</a></div></form>
<?php if($id): ?><form class="mt-4" method="post" action="/cms/blog/<?= $id ?>/delete"><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><button class="button-secondary" type="submit">Delete post</button></form><?php endif; ?>
<dialog id="media-picker"><form method="dialog"><div class="widget-heading"><h2 class="text-xl font-semibold">Choose an image</h2><button>Close</button></div><div class="media-grid mt-5"><?php foreach($media as $image): ?><button type="button" class="media-choice" data-media-url="/media/<?= (int)$image['id'] ?>" data-media-alt="<?= $escape($image['alt_text']) ?>"><img src="/cms/media/<?= (int)$image['id'] ?>" alt="<?= $escape($image['alt_text']) ?>"><span><?= $escape($image['original_name']) ?></span></button><?php endforeach; ?></div></form></dialog>
</section><script src="/assets/editor.js?v=1" defer></script>
